import Head from 'next/head';
import { Game, HomeComponent } from '@/components';
import { Player } from '@/types';
import { useAppSelector, useAppDispatch } from '@/hooks';

export default function Home() {
  const matched = useAppSelector((state) => state.game.matched);
  const showRecord = useAppSelector((state) => state.game.showRecord);
  const dispatch = useAppDispatch();

  return (
    <div
      style={{
        backgroundColor: 'inherit',
        backgroundImage: 'linear-gradient(180deg, #66809a 0%, #95d5e0 46%)',
      }}
    >
      <Head>
        <title>Tic Tac Toe </title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      {/* RENDERS HOME COMPONENT */}
      {!matched && <HomeComponent />}
      {/* RENDERS TIC TAC TOE BOARD */}
      {matched && !showRecord && <Game />}
      {/* RENDERS RECORD PAGE */}
    </div>
  );
}
